#!/bin/bash
echo "$0 <user> <group>"
user=$1
group=$2
[[ -z $2 ]] && exit

useradd --gid $group --home-dir /home/$group/$user $user

echo "Now make the homedir and edit /etc/passwd" 

cd  /var/yp
make
/etc/init.d/nis restart
