#!/bin/zsh

# cat /etc/dhcp3/dhcpd.conf | awk '/host/&&/fixed-address/&&!/#/{gsub("host","");gsub("{","");gsub("}","");gsub("hardware","");gsub("ethernet","");gsub(";","");gsub("fixed-address","");host=$1;ip=$3}' 


refresh_hosts() {
   echo "Refresh hosts"
   cat /etc/dhcp3/dhcpd.conf | awk '
      /^[[:space:]]*#/{next}
      /host /{n++;h[n]=$2}
      /fixed-address/{match($0,/fixed-address[[:space:]]*[[:digit:].]*/,a);split(a[0],b);ip[n]=b[2]}
      END{for(i=1;i<=n;i++)if(h[i]!~/b$/){print ip[i],h[i]}} '> /etc/hosts
   echo "127.0.0.1 localhost" >> /etc/hosts
}


refresh_rgang() {
   echo "Refresh rgang"
	cat /etc/hosts | grep -v "a" | awk '{print$2}' | grep "r[0-9]n" > /opt/cluster/etc/rgang/nodes
	cat /etc/hosts | awk '{print$2}' | grep nigol > /opt/cluster/etc/rgang/login
   cat /etc/hosts | grep -v "a" | awk '{print$2}' > /opt/cluster/etc/rgang/all
   cat /etc/hosts | grep -v "a" | awk '{print$2}' | grep "r1n" > /opt/cluster/etc/rgang/rack1
   cat /etc/hosts | grep -v "a" | awk '{print$2}' | grep "r2n" > /opt/cluster/etc/rgang/rack2
   cat /etc/hosts | grep -v "[0-9]a" | awk '{print$2}' | grep "nas"  > /opt/cluster/etc/rgang/nas
}

refresh_torque() {
   echo "Refresh torque"
   cat /etc/hosts | grep "r[0-9]n[0-9]" |grep -v "a" | awk '{print$2" np=4"}' > /opt/cluster/etc/queue/server_priv/nodes
   /etc/init.d/queue-server restart
   rgang all /etc/init.d/queue-client restart
}

refresh_users() {
   cd /var/yp
   make
   /etc/init.d/nis restart
}

refresh_hosts
refresh_rgang
refresh_torque
