#!/bin/zsh
. /opt/cluster/lib/common.shell

LOG "Updating goldnode"

LOG "Chrooting to goldnode"
chroot /opt/cluster/img/goldnode

LOG "Updating tar image"
cd /opt/cluster/img/goldnode 
tar cvzf ../goldnode.tar.gz .
