#!/bin/zsh
tmp=$CORVIX/tmp
for arch in i386 amd64; do
for distro in lenny etch sid;do
   url=http://ftp.de.debian.org/debian/dists/$distro/main/installer-$arch/current/images/netboot/netboot.tar.gz

   target=$CORVIX/isoimage/boot/$arch/$distro
   [[ -d $target ]] || mkdir -p $target
   tt=$tmp/$arch/$distro
   [[ -d $tt ]] || mkdir -p $tt
   [[ -e $tt/netboot.tar.gz ]] || wget $url -O $tt/netboot.tar.gz
   [[ -e $tt/debian-installer/$arch/initrd.gz ]] || tar xzf $tt/netboot.tar.gz -C $tt/
   cp $tt/debian-installer/$arch/initrd.gz $target/debian.gz
   cp $tt/debian-installer/$arch/linux $target/linux
done
done
