#!/bin/zsh
for f in $(find . -mindepth 1 -maxdepth 1 -type d); do
   echo Processing $f
   chmod -R 755 $f
   dpkg -b $f $f.deb || exit 1
   dpkg-sig -k corvix.eu -s corvix $f.deb || exit 2
done
cd ~/src/repository
./build
./publish
