#!/bin/zsh

url=http://ftp.de.debian.org/debian/dists/lenny/main/installer-i386/current/images/netboot/netboot.tar.gz

target=../tmp/isoimage/boot/

[[ -d tmp ]] || mkdir -p tmp
[[ -e tmp/netboot.tar.gz ]] || wget $url -O tmp/netboot.tar.gz
[[ -e tmp/debian-installer/i386/initrd.gz ]] || tar xzf tmp/netboot.tar.gz -C tmp
cp tmp/debian-installer/i386/initrd.gz $target
cp tmp/debian-installer/i386/linux $target

