#!/bin/zsh

initrd_unpack() {
initrd=$1
target=$2
[[ -z $2 ]] && target=initrd.tmp
[[ -e $target ]] && exit
mkdir $target
[[ ! -e $initrd ]] && exit
cd $target
fakeroot << endf
zcat ../$initrd | cpio -i --make-directories
endf
}

initrd_create() {
ONM=$2
[[ -d $1 ]] || exit
[[ -z $ONM ]] && ONM=$PWD/new-initrd
[[ -z $2 ]] && exit
cd $1
for i in `find . -name '*~'`; do rm $i; done
TM=/tmp/tmp-$$
fakeroot << endf
find .|cpio -H newc -o |gzip > $TM
endf
cd - > /dev/null 2>&1
mv $TM $ONM
echo "   done."
}


_fetch_initrd() {
   TREE=$1
   [[ -z $TREE ]] && exit 
   url=http://ftp.de.debian.org/debian/dists/$TREE/main/installer-i386/current/images/netboot/netboot.tar.gz
   echo "Fetching initrd:$none $url"
   [[ -d tmp/debian ]] || mkdir -p tmp/debian
   [[ -e tmp/debian/netboot.tar.gz ]] || wget $url -O tmp/debian/netboot.tar.gz
   [[ -e tmp/debian/debian-installer/i386/initrd.gz ]] || tar xzf tmp/debian/netboot.tar.gz -C tmp/debian
   [[ -d $initrd ]] && rm -rf $initrd
   initrd_unpack tmp/debian/debian-installer/i386/initrd.gz 
   mv initrd.tmp $initrd
}

_make_kernel_debian() {
   cp tmp/debian/debian-installer/i386/linux $target/linux
}

_make_initrd_debian() {
   echo "Make initrd: debian"
   cp patches/debian_preseed/* $initrd
   initrd_create $initrd $target/corvix.gz
}

_make_initrd_debian_preseed() {
   echo "Make initrd: debian preseed"
   cp patches/debian_preseed/* $initrd
   initrd_create $initrd $target/corvix.gz
}

_make_initrd_corvix() {
   "Make initrd: corvix"
   cp patches/common/* $initrd -r
   cp patches/corvix/* $initrd -r
   initrd_create $initrd $target/corvix.gz
}

_make_initrd_corvix_ch() {
   echo "Make initrd: corvix-ch"
   cp patches/common/* $initrd -r
   cp patches/head/* $initrd -r
   rm $initrd/preseed.cfg
   initrd_create $initrd $target/corvixch.gz
}  

_make_initrd() {
   _make_initrd_debian
   _make_initrd_debian_preseed
   _make_initrd_corvix
#   _make_initrd_corvix_ch
}


echo "Initrds..."
initrd=tmp/debian/initrd
target=../tmp/isoimage/boot
[[ -d $target ]] || mkdir -p $target
_fetch_initrd lenny
_make_kernel_debian
_make_initrd
