#!/bin/zsh
. common.shell

[[ $(id -u) == 0 ]] || DIE "No root..."

LOG "Installing egatrop to /opt/egatrop"
for d in lib ebuilds doc; do
   [[ -d /opt/egatrop/$d ]] || mkdir -p /opt/egatrop/$d
   cp -r $d /opt/egatrop/
done
chmod -R aog+rx /opt/egatrop

[[ -d /opt/egatrop/src ]] || mkdir -p /opt/egatrop/src
chmod -R aog+rwx /opt/egatrop/src

#echo "PATH=$PATH:/opt/egatrop/lib"
