#!/bin/zsh
. common.shell

DEV=$1
[[ -e $DEV || -n $DEV ]] || DIE "Missing device: $DEV"

_prepare_software() {
   sudo apt-get install mbr mtools syslinux dosfstools
}

_make_fs_dos() {
   LOG "Create boot stick on $none$DEV"
   LOG "Now create the partitions.$none   n p 1 (>50MB) a 1 t 6  w"
   PAUSE "ok?"
   sudo fdisk $DEV

   PART=1
   LOG "Create filesystem on $none$DEV$PART"
   PAUSE "ok?"
   sudo mkdosfs -v -n corvix $DEV$PART

   SYSLINUX=syslinux
   LOG "Make bootable."
   sudo $SYSLINUX -s $DEV$PART
}

_old_bios() {
   LOG "Fake zip-fashion"
   sudo mkdiskimage -$PART $DEV 0 64 32
}

_fix_mbr() {
   sudo install-mbr $DEV
}

_fix_mbr
_make_fs_dos

IMG=./tmp/stickimage
[[ -d $IMG ]] || mkdir -p $IMG
LOG "Mount on $none$IMG"
sudo mount $DEV$PART $IMG
sudo cp ./tmp/isoimage/* $IMG -r
sudo umount $DEV$PART
