#!/bin/zsh

echo "You need: dhcpd, tftp-hpa"
echo "Ok?"
read

sudo apt-get install dhcpd tftpd-hpa

echo "You want to look at our corvix /etc/dhcpd.conf, /etc/tftp"
echo "Ok?"
read

echo "Copying files"
[[ -e /srv/tftp ]] || mkdir -p /srv/tftp
cp tmp/isoimage/* /srv/tftp -r
