#!/bin/zsh

DEV=$1

[[ -z $DEV ]] && exit
[[ -e $DEV ]] || exit

_prepare_software() {
   sudo apt-get install mbr mtools syslinux dosfstools
}

_make_fs_dos() {
   echo "Create boot stick on $none$DEV"
   echo "Now create the partitions.$none\nWe assume an empty stick! Please clean all partitions yourself."
   echo "This is your stick now"
   sudo fdisk -l $DEV
   echo "Do you want to me to fire up fdisk now for deletions?"
   read -s -k 1 i
   case $i in 
      y|Y|j) sudo fdisk $DEV
   esac
   echo "Now creating new partitions. Ok?"
   read
   echo -ne "\nn\np\n1\n1\n+50M\na\n1\nt\n6\nw\n"| sudo fdisk $DEV

   PART=1
   echo "Create filesystem on $none$DEV$PART"
   echo "ok?"
   read
   sudo mkdosfs -v -n corvix $DEV$PART

   SYSLINUX=syslinux
   echo "Make bootable."
   sudo $SYSLINUX -s $DEV$PART
}

_old_bios() {
   echo "Fake zip-fashion"
   sudo mkdiskimage -$PART $DEV 0 64 32
}

_fix_mbr() {
   sudo install-mbr $DEV
}

_fix_mbr
_make_fs_dos

IMG=./tmp/stickimage
[[ -d $IMG ]] || mkdir -p $IMG
echo "Mount on $none$IMG with device $DEV$PART"
sudo mount $DEV$PART $IMG
echo "Copy files"
sudo cp ./tmp/isoimage/* $IMG -r
sudo umount $DEV$PART
