#!/bin/zsh
./clean
# copy .deb files
cp ../deb-package/*deb dists/testing
# create & sign package list
apt-ftparchive packages dists/testing |gzip >dists/testing/Packages.gz
# create & sign release file
apt-ftparchive release ./dists/ > ./dists/Release
[[ -e dists/Release.gpg ]] && rm dists/Release.gpg 
gpg -u corvix.eu -abs -o dists/Release.gpg dists/Release
