#!/bin/zsh
find pool -type f -exec rm {} \;
find dists -type f -exec rm {} \;

_copy_debs() {
cp ../deb-package/*deb pool
}

_create_release() {
cat << eof > dists/$suit/Release
Origin: corvix
Label: corvix
Suite: $suit
Version: $vers
Codename: corvix
Architectures: $archs
Components: $comps
Description: http://corvix.eu
eof
apt-ftparchive release dists/$suit >> dists/$suit/Release
[[ -e dists/$suit/Release.gpg ]] && rm dists/$suit/Release.gpg
gpg -u corvix.eu -abs -o dists/$suit/Release.gpg dists/$suit/Release
}   

_create_arch() {
apt-ftparchive packages pool > $dir/Packages
cat << eof > $dir/Release
Archive: $suit
Component: $comp
Origin: corvix
Label: corvix
Architecture: $arch
eof
}

archs="i386 alpha"
comps=meta
suit=testing
comp=meta

_copy_debs

for arch in $(echo $archs); do
   dir=dists/$suit/$comp/binary-$arch
   _create_arch 
done
_create_release dists/$comp

#cd dists/testing
#apt-ftparchive packages . |gzip >Packages.gz
# create & sign release file
#apt-ftparchive release . > ./Release
#[[ -e Release.gpg ]] && rm Release.gpg 
#gpg -u corvix.eu -abs -o Release.gpg Release
