#!/bin/bash
ppp=/usr/sbin
qqq=/opt/corvix/
case "$1" in
  start)
        echo "Starting pbs client: "
        $ppp/pbs_mom
        ;;
  stop)
        echo "Shutting down pbs client: "
        killall -KILL pbs_mom
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
exit 0
