#!/bin/zsh
for f in $(find . -mindepth 1 -maxdepth 1 -type d); do
   echo Processing $f
   chmod -R 755 $f
   deb=$f.deb
   dpkg -b $f $deb
   dpkg-sig -k corvix.eu -s corvix $deb
   ../../repository/dput $deb testing/meta
   rm  $deb
done
