#!/bin/zsh
ver_maui=3.2.6p19
ver_torque=2.1.6

_prepare() {
   [[ -d /usr/src/cluster ]] || mkdir -p /usr/src/cluster
   cd /usr/src/cluster

   [[  -e /usr/src/cluster/torque-$ver_torque.tar.gz ]] || wget http://10.1.1.1/corvix/torque-$ver_torque.tar.gz
   [[ -e /usr/src/cluster/maui-$ver_maui.tar.gz ]] || wget http://10.1.1.1/corvix/maui-$ver_maui.tar.gz

   tar xzf torque-$ver_torque.tar.gz
   tar xzf maui-$ver_maui.tar.gz
}

_compile_torque() {
   cd /usr/src/cluster/torque-$ver_torque
   ./configure --enable-monitor --enable-clients --enable-syslog
   make -j 4
   make install
}   
_compile_maui() {   
   cd /usr/src/cluster/maui-$ver_maui
   export MAUIADMIN=root
   ./configure --with-spooldir=/var/spool/torque --with-pbs=/usr/local
   make -j 4
   make install
}

_postinstall() {
   chmod aog+rwx /var/spool/torque/spool
}

_prepare
_compile_torque
_compile_maui
_postinstall
