#!/bin/zsh
_config_client() {
cat << eof >> $target/etc/group
+:::
eof

cat << eof >> $target/etc/passwd
+::::::
eof

update-rc.d -f nis remove
update-rc.d nis defaults 98
}


cat << eof > /etc/default/nis
NISSERVER=false
NISCLIENT=yes
eof

_config_client
