#!/bin/zsh
_exchange() {
   echo "   exchange $1 by $2"
   [[ -e $1 ]] && rm -rf $1
   ln -s $2 $1
}

_login() {
   _exchange /etc/profile /opt/cluster/etc/login/profile
}

_nis() {
   _exchange /etc/default/nis /opt/cluster/etc/nis/nis
   _exchange /etc/defaultdomain /opt/cluster/etc/nis/defaultdomain
   _exchange /etc/ypserv.securenets /opt/cluster/etc/nis/ypserv.securenets
   _exchange /var/yp/Makefile /opt/cluster/etc/nis/Makefile
   _exchange /etc/nsswitch.conf /opt/cluster/etc/nis/nsswitch.conf
}

_queue() {
   _exchange /var/spool/torque/maui.cfg /opt/cluster/etc/queue/maui.cfg
   _exchange /var/spool/torque/servername /opt/cluster/etc/queue/server_name
   _exchange /var/spool/torque/mom_priv/config /opt/cluster/etc/queue/mom_priv/config
   _exchange /var/spool/torque/mom_priv/epilogue /opt/cluster/etc/queue/mom_priv/epilogue.parallel
   _exchange /var/spool/torque/mom_priv/epilogue /opt/cluster/etc/queue/mom_priv/epilogue.parallel
   _exchange /var/spool/torque/server_priv/nodes /opt/cluster/etc/queue/server_priv/nodes
}

_queue_client() {
   _exchange /etc/init.d/queue-client /opt/cluster/etc/init/queue-client
   _exchange /etc/rc2.d/S69queue-client /opt/cluster/etc/init/queue-client
}


mkdir -p /opt/cluster
echo 10.1.1.1:/opt/cluster /opt/cluster nfs defaults,user,auto,exec 0 0 >> /etc/fstab
chmod aog+rx /opt
chmod aog+rx /opt/cluster
mount /opt/cluster

_login 
_queue
_queue_client
