#!/bin/zsh
[[ -z $CORVIX ]] && export CORVIX=$PWD/

cd initrd
./_build
cd ..

cd syslinux
./_build
cd ..

[[ -e isoimage/isolinux/isolinux.bin ]] || exit
[[ -e isoimage/isolinux/boot.cat ]] || exit
cd isoimage
mkisofs -R -V corvix_bootcd -o ../corvix.iso -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -J -r -q -boot-info-table ./
cd ..
