#!/bin/zsh
ver_maui=3.2.6p19
ver_torque=2.1.6

_prepare() {
   [[ -d /usr/src/cluster ]] || mkdir -p /usr/src/cluster
   cd /usr/src/cluster

   [[ -e torque-$ver_torque.tar.gz ]] || wget http://www.clusterresources.com/downloads/torque/torque-$ver_torque.tar.gz
   [[ -e maui-$ver_maui.tar.gz ]] || wget http://www.clusterresources.com/downloads/maui/maui-$ver_maui.tar.gz

   tar xzf torque-$ver_torque.tar.gz
   tar xzf maui-$ver_maui.tar.gz
}

_compile_torque() {
   cd /usr/src/cluster/torque-$ver_torque
   ./configure --enable-server --enable-monitor --enable-clients --enable-syslog
   make -j 4
   make install
}   
_compile_maui() {   
   cd /usr/src/cluster/maui-$ver_maui
   export MAUIADMIN=root
   ./configure --with-spooldir=/var/spool/torque --with-pbs=/usr/local
   make -j 4
   make install
}

_make_mirror() {
   cp /usr/src/cluster/torque-$ver_torque.tar.gz /opt/cluster/lib/www/corvix/
   cp /usr/src/cluster/maui-$ver_maui.tar.gz /opt/cluster/lib/www/corvix/
}

_postinstall() {
   chmod aog+rwx /var/spool/torque/spool
}

_prepare
_compile_torque
_compile_maui
_postinstall
_make_mirror
