#!/bin/zsh
ver_maui=3.2.6p19
ver_torque=2.1.6

_prepare() {
   [[ -d /usr/src/cluster ]] || mkdir -p /usr/src/cluster
   cd /usr/src/cluster

   [[ -e torque-$ver_torque.tar.gz ]] || wget http://www.clusterresources.com/downloads/torque/torque-$ver_torque.tar.gz
   [[ -e maui-$ver_maui.tar.gz ]] || wget http://www.clusterresources.com/downloads/maui/maui-$ver_maui.tar.gz

   tar xzf torque-$ver_torque.tar.gz
   tar xzf maui-$ver_maui.tar.gz
}

_compile_torque() {
   cd /usr/src/cluster/torque-$ver_torque
   ./configure --enable-server --enable-monitor --enable-clients --enable-syslog
   make -j 4
   make install
}   
_compile_maui() {   
   cd /usr/src/cluster/maui-$ver_maui
   export MAUIADMIN=root
   ./configure --with-spooldir=/var/spool/torque --with-pbs=/usr/local --with-key=666
   make -j 4
   make install
}

_make_mirror() {
   cp /usr/src/cluster/torque-$ver_torque.tar.gz /opt/cluster/lib/www/corvix/
   cp /usr/src/cluster/maui-$ver_maui.tar.gz /opt/cluster/lib/www/corvix/
}

_configure_queue() {
echo "Warning! Use internal hostname only."
read
/usr/local/sbin/pbs_server -t create
cat << eof | qmgr 
#
# Create queues and set their attributes.
#
#
# Create and define queue batch
#
#create queue batch
set queue batch queue_type = Execution
set queue batch acl_host_enable = False
#set queue batch resources_max.nodect = 6
set queue batch resources_default.nodes = 1
set queue batch resources_default.walltime = 01:00:00
#set queue batch resources_available.nodect = 18
set queue batch enabled = True
set queue batch started = True
#
# Set server attributes.
#
set server scheduling = True
#set server managers += scott@*.icluster.org
#set server managers += wightman@*.icluster.org
#set server operators += scott@*.icluster.org
#set server operators += wightman@*.icluster.org
set server default_queue = batch
set server log_events = 511
set server mail_from = adm
#set server resources_available.nodect = 80
set server scheduler_iteration = 600
set server node_ping_rate = 300
set server node_check_rate = 600
set server tcp_timeout = 6
#submit hosts
set server submit_hosts += nigol1
set server submit_hosts += nigol2
set server submit_hosts += head
set server managers += root@nigol1
set server operators += root@nigol1
set server managers += root@nigol2
set server operators += root@nigol2
# mailing
set server mail_from="wap@physik.uni-kl.de"
eof
qterm
}

_postinstall() {
   chmod aog+rwx /var/spool/torque/spool
   _configure_queue
   _make_mirror
   ./install-00opt
}

_prepare
_compile_torque
_compile_maui
_postinstall
