#!/bin/zsh

. common.shell

[[ -z $MIRROR ]] && MIRROR="" #mirror.corvix.eu
[[ -z $EBASE ]] && EBASE=/opt/egatrop
[[ -z $LOGFLE ]] && LOGFILE=$EBASE/log/egatrop
[[ -z $ESRC_DIR ]] && ESRC_DIR=$EBASE/src/
[[ -z $EBIN_DIR ]] && EBIN_DIR=$EBASE

_ename() {
   EFULL=$(basename $EBUILD | sed 's/.ebuild//g')
   ENAME=$(echo $EFULL | awk '{gsub("-"," ");gsub(".ebuild","");print$1}')
   EVERS=$(echo $EFULL | awk '{gsub("-"," ");gsub(".ebuild","");print$2}')
   EREL=$(echo $EFULL | awk '{gsub("-"," ");gsub(".ebuild","");print$3}')
   ILOG=$EBASE/log/$ENAME.installed
}   

_logo() {
   LOGLEVEL=`expr $LOGLEVEL+1`
   LOG "Egatrop: installing ebuild $EFULL"
   LOGLEVEL=`expr $LOGLEVEL+1`
   LOG "using: esrc=$ESRC_DIR ebin=$EBIN_DIR"
}

_efetch() {
   LOG "uris: $ESRC_URI"
   for uri in $(echo $ESRC_URI); do
      file=${uri##*/}
      [[ -n $MIRROR ]] && uri=$MIRROR/$file
      if [[ ! -e $ESRC_DIR/$file ]]; then 
         LOG "downloading $file from $uri"
         _ wget $uri
      fi
   done
}

_ecalc_md5sums() {
   LOG "calculating md5sums"
   for uri in $(echo $ESRC_URI); do
      file=${uri##*/}
      [[ -n $MIRROR ]] && uri=$MIRROR/$file
      md5sum $file
   done
}

_emd5check() {
   LOG "checking md5sums"
   echo "$EMD5" | md5sum -c || DIE "Wrong md5sum"
}

_epython() {
   LOG "pyhton wrapper"
   cmd=${@/install/install $_PREFIX --force --record=$ILOG}
   _esu python $(echo $cmd)
}

_einstall() {
   LOG "Installing"
   _esu make install > $TMP
   cat $TMP | grep "/usr/bin/install" | awk '{print $NF}' >> $ILOG 
   rm -f $TMP
}


_euninstall() {
   LOG "Uninstalling"
   for f in $(cat $ILOG); do
      _esu rm -f $f
   done
   rm -f $ILOG
}

_esu() {
   _ sudo "$@"
}

_is_installed() {
   return $(test -e $ILOG)
}

_is_python() {
   return $(test -e setup.py )
}

_has_configure() {
   return $(test -e configure )
}



_eunpack() {
   DIE "Not working"
   for uri in $(echo $ESRC_URI); do
      local file=${uri##*/}

      LOG "Unpack:" $file
      cd $ETMP

      f=$EARCH_DIR/$file
      ff=${f%.*}
      fff=${ff##*.}
      ffff=${f##*.}

      case $ffff in
         tar) _rr tar xof $f ;;
         tgz) _rr tar xozf $f ;;
         tbz|tbz2)
            _rr bzip2 -dc $f | tar xof -
            ;;
         ZIP|zip|jar)
            _rr unzip -qo $f 
            ;;
         gz|Z|z)
            if [[ "${fff}" == "tar" ]]; then
               _rr tar zoxf $f 
            else
               _rr gzip -dc $f > ${ff} 
            fi
            ;;
         bz2|bz)
            if [[ "${fff}" == "tar" ]]; then
               _rr bzip2 -dc $f | tar xof - 
            else
               _rr bzip2 -dc $f > $ff 
            fi
            ;;
         RAR|rar) _rr unrar x -idq -o+ $f ;;
         LHa|LHA|lha|lzh) _rr lha xfq $f ;;
         a|deb) _rr ar x $f ;;
         lzma)
            if [ $fff == "tar" ]; then
               _rr lzma -dc $f | tar xof - 
            else
               _rr lzma -dc $f > $ff || die 1 "err"
            fi
            ;;
         *)
            die 1 "unpack $f: file format not recognized. Ignoring."
            ;;
      esac
   done    
   _find_edirs
   src_unpack
}

_ename
_logo
_is_installed && DIE "Already installed: $ILOG exists."

cd $ESRC_DIR
