#!/bin/zsh
. common.shell

LOG "Installing debian mirror"

_install_pkg apt-mirror
PAUSE "NB: /opt/cluster/etc/apt/mirror.list /opt/cluster/pxeboot/mirror"
LOG "Start to mirror in background"
#apt-mirror 2>/dev/null 1>/dev/null &
PAUSE DISABLED
