#!/bin/zsh
_exchange() {
   echo "   exchange $1 by $2"
   [[ -e $1 ]] && rm -rf $1
   ln -s $2 $1
}   

_login() {
   _exchange /etc/profile /opt/cluster/etc/login/profile
}   

_networking() {
   _exchange /etc/hosts /opt/cluster/etc/dns/hosts
   _exchange /etc/dhcpd.conf /opt/cluster/etc/dhcp/dhcpd.conf
#   _exchange /etc/network/interfaces /opt/cluster/etc/network/interfaces
}   

_ganglia() {
   _exchange /etc/gmond.conf /opt/cluster/etc/ganglia/gmond.conf
   _exchange /etc/gmetad.conf /opt/cluster/etc/ganglia/gmetad.conf
}   

_mirror() { 
   _exchange /etc/apt/mirror.list /opt/cluster/etc/apt/mirror.list
   _exchange /var/spool/apt-mirror/mirror /opt/cluster/lib/www/mirror
}   

_www() {
   _exchange /var/www /opt/cluster/lib/www
}   

_nfs() {
   _exchange /etc/exports /opt/cluster/etc/nfs/exports
}   

_nis() {
   _exchange /etc/default/nis /opt/cluster/etc/nis/nis
   _exchange /etc/defaultdomain /opt/cluster/etc/nis/defaultdomain
   _exchange /etc/ypserv.securenets /opt/cluster/etc/nis/ypserv.securenets
   _exchange /var/yp/Makefile /opt/cluster/etc/nis/Makefile
   _exchange /etc/nsswitch.conf /opt/cluster/etc/nis/nsswitch.conf
}

_pxeboot() {
   _exchange /etc/default/tftpd-hpa /opt/cluster/etc/tftp/tftpd-hpa
}   

_queue() {
   _exchange /var/spool/torque/maui.cfg /opt/cluster/etc/queue/maui.cfg
   _exchange /var/spool/torque/servername /opt/cluster/etc/queue/server_name
   _exchange /var/spool/torque/mom_priv/config /opt/cluster/etc/queue/mom_priv/config
   _exchange /var/spool/torque/mom_priv/epilogue /opt/cluster/etc/queue/mom_priv/epilogue.parallel
   _exchange /var/spool/torque/mom_priv/epilogue /opt/cluster/etc/queue/mom_priv/epilogue.parallel
   _exchange /var/spool/torque/server_priv/nodes /opt/cluster/etc/queue/server_priv/nodes
}  

mkdir /opt/cluster -p
cp opt/* /opt/cluster -r

_login
_networking
_ganglia
_mirror
_www
_nfs
_nis
_pxeboot
_queue
