#!/bin/zsh
PATH=$PATH:/opt/cluster/bin:/opt/cluster/sbin:/opt/cluster/lib
export PATH

_configure_zsh() {
   chsh -s /bin/zsh root
   echo -ne ". /etc/profile" > /root/.zshrc
   echo -ne "PATH=$PATH" >> /etc/profile
   . /root/.zshrc
}

_configure_debian() {
   distro=lenny
cat << eof > $root/etc/apt/sources.list
deb http://ftp.uni-kl.de/debian/ $distro main contrib non-free
deb-src http://ftp.uni-kl.de/debian/ $distro main contrib non-free

deb http://security.debian.org/ $distro/updates main contrib
deb-src http://security.debian.org/ $distro/updates main contrib

deb ftp://ftp.uni-kl.de/debian-multimedia $distro main
deb-src ftp://ftp.uni-kl.de/debian-multimedia $distro main
eof

   sudo apt-get update
   sudo apt-get -y --force-yes install debian-multimedia-keyring
   sudo apt-get update
}


_configure_zsh
_configure_debian


for list in $(find ./packages/ -name "*" -type f); do
   for pkg in $(cat $list); do
      sudo apt-get -y --force-yes install $pkg
   done
done

LOG "Processing installation scripts"
for script in $(find . -name "install-*" | sort); do
   _ $script
done
