#!/bin/zsh
PATH=$PATH:/opt/cluster/bin:/opt/cluster/sbin:/opt/cluster/lib
export PATH

_configure_zsh() {
   chsh -s /bin/zsh root
   echo -ne ". /etc/profile" > /root/.zshrc
   echo -ne "PATH=$PATH" >> /etc/profile
   . /root/.zshrc
}

_configure_debian() {
   distro=lenny
cat << eof > $root/etc/apt/sources.list
deb http://10.1.1.1/mirror/ftp.uni-kl.de/debian/ $distro main contrib non-free
deb-src http://10.1.1.1/mirror/ftp.uni-kl.de/debian/ $distro main contrib non-free

deb http://10.1.1.1/mirror/security.debian.org/ $distro/updates main contrib
deb-src http://10.1.1.1/mirror/security.debian.org/ $distro/updates main contrib

deb ftp://10.1.1.1/mirror/ftp.uni-kl.de/debian-multimedia $distro main
deb-src ftp://10.1.1.1/mirror/ftp.uni-kl.de/debian-multimedia $distro main
eof

   apt-get update
   apt-get -y --force-yes install debian-multimedia-keyring
   apt-get update
   apt-get -y --force-yes install nfs-common
   apt-get -y --force-yes upgrade
   apt-get dist-upgrade
}


_configure_zsh
_configure_debian


for list in $(find ./packages/ -name "*" -type f); do
   for pkg in $(cat $list); do
      apt-get -y --force-yes install $pkg
   done
done

for script in $(find . -name "install-*" | sort); do
   _ $script
done
