#!/bin/zsh
echo "Syslinux..."

_fetch_sources() {
   echo "Preparing isolinux..."
   ESRC_URI=http://www.kernel.org/pub/linux/utils/boot/syslinux/syslinux-$vers.tar.gz
   [[ -d $tmp ]] || mkdir $tmp
   [[ -e $tmp/syslinux-$vers.tar.gz ]] && return 0
   wget $ESRC_URI -O $tmp/syslinux-$vers.tar.gz
   #_ sudo apt-get -y --force-yes build-dep syslinux
   cwd=$PWD
   cd $tmp
   tar xzf syslinux-$vers.tar.gz
   cd $cwd
}

_make_isolinux() {
   echo "Make isolinux image"
   [[ -d $target/isolinux ]] || mkdir -p $target/isolinux
   cp $tmp/syslinux-$vers/core/isolinux.bin $target/isolinux
   cp patches/* $target/isolinux
   cp splash/splash.rle $target/isolinux
}

_make_syslinux() {
   echo "Make syslinux image"
   [[ -d $target ]] || mkdir -p $target
   cp patches/* $target
   cp splash/splash.rle $target
}

_make_pxelinux() {
   echo "Make pxelinux image"
   [[ -d $target/pxelinux.cfg ]] || mkdir -p $target/pxelinux.cfg
   cp $tmp/syslinux-$vers/core/pxelinux.0 $target/pxelinux.0
   cat patches/syslinux.cfg > $target/pxelinux.cfg/default
}

_splash() {
   echo "Splash image"
   #cd splash
   #pngtopnm splash.png | gzip -9 > splash.ppm.gz
   #gzip -cd splash.ppm.gz | ppmtolss16 \#000000=0 \#d0d0d0=7 \#f6f6f6=15 > splash.lss
   #cp splash.lss $target
   #cd ..
}

[[ -z $CORVIX ]] && exit 1
vers=3.70
target=$CORVIX/isoimage
tmp=$CORVIX/tmp
[[ ! -e $target ]] && mkdir -p $target
_fetch_sources
_make_syslinux
_make_isolinux
_make_pxelinux
