#!/bin/bash
black="\033[0;30m"
dark_gray="\033[1;30m"
blue="\033[0;34m"
light_blue="\033[1;34m"
green="\033[0;32m"
light_green="\033[1;32m"
cyan="\033[0;36m"
light_cyan="\033[1;36m"
red="\033[0;31m"
light_red="\033[1;31m"
purple="\033[0;35m"
light_purple="\033[1;35m"
brown="\033[0;33m"
yellow="\033[1;33m"
light_gray="\033[0;37m"
white="\033[1;37m"
none="\033[0m"

g=$green 
r=$red
w=$light_gray

echo -ne "  .~.      \n"
echo -ne "  ${dark_gray}/${brown}V${dark_gray}\\\ ${yellow}Welcome to `hostname`     \n"
echo -ne " ${dark_gray}/${none}/ \\\\${dark_gray}\\\     \n"
echo -ne "${dark_gray}/${none}(   )${dark_gray}\\\    \n"
echo -ne " ${brown}^${none}\`~'${brown}^${none}     \n"


#echo -ne $g'               \||/\n'
#echo -ne $g'                 |  '$r'@'$g'___oo  \n'
#echo -ne $g'       /\  /\   / (__'$w',,,,'$g'|      '$yellow'Welcome to '`hostname`' \n'
#echo -ne $g'      ) /^\) ^\/ _)\n'
#echo -ne $g'      )   /^\/   _) \n'
#echo -ne $g'      )   _ /  / _)\n'
#echo -ne $g'  /\  )/\/ ||  | )_)    \n'
#echo -ne $g' <  >      |('$w',,'$g') )__)\n'
#echo -ne $g'  ||      /    \)___)\ \n'
#echo -ne $g'  | \____(      )___) )___\n'
#echo -ne $g'   \______(_______'$w';;;'$g' __'$w';;;'$g'\n'$w
