#!/bin/bash
case "$1" in
  start)
        echo "Starting torque server: "
        /usr/local/sbin/pbs_mom
        /usr/local/sbin/pbs_server
        echo "Starting maui scheduler: "
        /usr/local/maui/sbin/maui
        for job in `/usr/local/maui/bin/showq | awk '/Deferred/{print$1}'`; do 
		     echo Fixing job: $job; 
		     runjob -c $job; 
		     releasehold $job; 
	     done

        ;;
  stop)
        echo "Shutting down maui scheduler: "
        killall -KILL pbs_sched maui
        echo "Shutting down torque server: "
        killall -KILL pbs_server
        killall -KILL pbs_mom
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage: torque {start|stop|restart}"
        exit 1
esac
exit 0
