#!/bin/sh
_config_logins() {
cat << eof >> /etc/group
+:::
eof

cat << eof >> /etc/passwd
+::::::
eof

cat << eof >> /etc/shadow
+::::::::
eof
}

_config_service() {
update-rc.d -f nis remove
update-rc.d nis defaults 98
}

_config_logins
_config_service
