#!/bin/zsh



refresh_rgang() {
   echo "Refresh rgang"
	cat /etc/hosts | grep -v "a" | awk '{print$2}' | grep "r[0-9]n" > /opt/cluster/etc/rgang/nodes
	cat /etc/hosts | awk '{print$2}' | grep nigol > /opt/cluster/etc/rgang/login
   cat /etc/hosts | grep -v "a" | awk '{print$2}' > /opt/cluster/etc/rgang/all
   cat /etc/hosts | grep -v "a" | awk '{print$2}' | grep "r1n" > /opt/cluster/etc/rgang/rack1
   cat /etc/hosts | grep -v "a" | awk '{print$2}' | grep "r2n" > /opt/cluster/etc/rgang/rack2
   cat /etc/hosts | grep -v "[0-9]a" | awk '{print$2}' | grep "nas"  > /opt/cluster/etc/rgang/nas
}

refresh_torque() {
   echo "Refresh torque"
   cat /etc/hosts | grep "r[0-9]n[0-9]" |grep -v "[0-9]a" | awk '{print$2" np=4"}' > /opt/cluster/etc/queue/server_priv/nodes
   cat /etc/hosts | grep "nigol[0-9]" |grep -v "[0-9]a" | awk '{print$2" np=4"}' >> /opt/cluster/etc/queue/server_priv/nodes
   cat /etc/hosts | grep "head" |grep -v "[0-9]a" | awk '{print$2" np=4"}' >> /opt/cluster/etc/queue/server_priv/nodes
   /etc/init.d/queue-server restart
   rgang all /etc/init.d/queue-client restart
}

